# Parte 4 – NumPy

**Assignment 1 – Fundamentos de Python**  
**Diplomado en Ciencia de Datos – PUCP | Grupo 9**

NumPy es la librería base del cálculo numérico en Python. Su estructura
principal es el **array**, que a diferencia de una lista guarda todos sus
elementos del mismo tipo y en un bloque contiguo de memoria. Eso permite
aplicar una operación sobre todos los elementos a la vez (*vectorización*),
sin escribir bucles y de forma mucho más rápida.

Esta sección cubre los requisitos del enunciado y añade ejercicios
complementarios de práctica.

## 1. Importar NumPy

Se importa con el alias `np`, que es la convención estándar.

In [1]:
import numpy as np

print(f"NumPy importado correctamente — versión {np.__version__}")

NumPy importado correctamente — versión 2.5.3


## 2. Crear un array con los números del 1 al 10

`np.arange(inicio, fin)` genera los valores desde `inicio` hasta `fin - 1`:
el límite superior es **excluyente**, por eso se escribe `11` para llegar
al 10.

In [2]:
numeros = np.arange(1, 11)

print(f"Array del 1 al 10: {numeros}")

Array del 1 al 10: [ 1  2  3  4  5  6  7  8  9 10]


## 3. Valor máximo y mínimo

Se guardan en variables para no recorrer el array dos veces dentro de los
`print`. Las funciones `np.max()` / `np.min()` y los métodos equivalentes
`numeros.max()` / `numeros.min()` hacen exactamente lo mismo.

In [3]:
valor_maximo = numeros.max()
valor_minimo = numeros.min()

print(f"Valor máximo: {valor_maximo}")
print(f"Valor mínimo: {valor_minimo}")

Valor máximo: 10
Valor mínimo: 1


## 4 y 5. Array de 5 ceros y array de 5 unos

`np.zeros()` y `np.ones()` crean arrays del tamaño indicado rellenos con ese
valor. Por defecto son de tipo `float64`, por eso se imprimen como `0.` y `1.`
en lugar de `0` y `1`.

In [4]:
ceros = np.zeros(5)
unos = np.ones(5)

print(f"Array de 5 ceros: {ceros}")
print(f"Array de 5 unos : {unos}")
print(f"Tipo de dato    : {ceros.dtype}")

Array de 5 ceros: [0. 0. 0. 0. 0.]
Array de 5 unos : [1. 1. 1. 1. 1.]
Tipo de dato    : float64


## 6, 7 y 8. Crear la matriz, mostrarla y ver sus dimensiones

`np.array()` construye un array a partir de listas anidadas: cada lista interna
es una fila. El atributo `.shape` devuelve una tupla `(filas, columnas)`.

In [5]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matriz:")
print(matrix)
print()
print(f"Dimensiones de la matriz: {matrix.shape}")

Matriz:
[[1 2 3]
 [4 5 6]]

Dimensiones de la matriz: (2, 3)


---

# Ejercicios adicionales

Los requisitos del enunciado terminan en el punto anterior. Lo que sigue es
práctica complementaria del grupo sobre atributos de arrays, indexación y
operaciones estadísticas.

## Atributos de un array

Todo array expone atributos que describen su estructura, sin necesidad de
recorrerlo:

| Atributo | Qué indica |
| --- | --- |
| `.shape` | forma: filas y columnas |
| `.ndim` | número de dimensiones (1 = vector, 2 = matriz) |
| `.size` | cantidad total de elementos |
| `.dtype` | tipo de dato de los elementos |

In [6]:
datos = np.array([10, 20, 30, 40, 50])

print(f"Array        : {datos}")
print(f"Forma        : {datos.shape}")
print(f"Dimensiones  : {datos.ndim}")
print(f"N° elementos : {datos.size}")
print(f"Tipo de dato : {datos.dtype}")

Array        : [10 20 30 40 50]
Forma        : (5,)
Dimensiones  : 1
N° elementos : 5
Tipo de dato : int64


## Matriz de 3x3

Los mismos atributos aplicados a una matriz. Nótese que ahora `.ndim` es 2 y
`.size` es 9, es decir, filas por columnas.

In [7]:
matriz = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Matriz 3x3:")
print(matriz)
print()
print(f"Forma: {matriz.shape} | Dimensiones: {matriz.ndim} | N° elementos: {matriz.size}")

Matriz 3x3:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Forma: (3, 3) | Dimensiones: 2 | N° elementos: 9


## Indexación de filas y columnas

En una matriz se indica `[fila, columna]`. Los dos puntos `:` significan
"todos", por lo que `matriz[0, :]` es la primera fila completa y `matriz[:, 1]`
es la segunda columna completa.

In [8]:
print(f"Elemento en fila 1, columna 1: {matriz[1, 1]}")
print(f"Primera fila                 : {matriz[0, :]}")
print(f"Segunda columna              : {matriz[:, 1]}")

Elemento en fila 1, columna 1: 50
Primera fila                 : [10 20 30]
Segunda columna              : [20 50 80]


## Operaciones estadísticas

Estas funciones recorren toda la matriz y devuelven un solo valor. No hace
falta ningún bucle: NumPy opera sobre el array completo.

In [9]:
print(f"Suma total   : {matriz.sum()}")
print(f"Promedio     : {matriz.mean()}")
print(f"Valor máximo : {matriz.max()}")
print(f"Valor mínimo : {matriz.min()}")

Suma total   : 450
Promedio     : 50.0
Valor máximo : 90
Valor mínimo : 10


## Promedios por eje

El parámetro `axis` define la dirección del cálculo:

- `axis=0` recorre **las filas** hacia abajo, así que devuelve un promedio
  **por columna**.
- `axis=1` recorre **las columnas** hacia el costado, así que devuelve un
  promedio **por fila**.

In [10]:
print(f"Promedio por columna (axis=0): {matriz.mean(axis=0)}")
print(f"Promedio por fila    (axis=1): {matriz.mean(axis=1)}")

Promedio por columna (axis=0): [40. 50. 60.]
Promedio por fila    (axis=1): [20. 50. 80.]


## Conclusión

NumPy permite aplicar operaciones sobre todos los elementos de un array a la
vez, sin escribir bucles. Los atributos `.shape`, `.ndim`, `.size` y `.dtype`
describen la estructura del array, mientras que funciones como `sum()`,
`mean()`, `max()` y `min()` resumen su contenido. El parámetro `axis` permite
además calcular esos resúmenes por fila o por columna.