# Parte 4 – NumPy

**Assignment 1 – Fundamentos de Python**  
**Diplomado en Ciencia de Datos – PUCP | Grupo 9**

NumPy es la librería base del cálculo numérico en Python. Su estructura
principal es el **array**, que a diferencia de una lista guarda todos sus
elementos del mismo tipo y en un bloque contiguo de memoria. Eso permite
aplicar una operación sobre todos los elementos a la vez (*vectorización*),
sin escribir bucles y de forma mucho más rápida.

Esta sección cubre los requisitos del enunciado y añade ejercicios
complementarios de práctica.

> Se sigue el mismo formato que en las otras partes: expresión suelta cuando la
> celda muestra un solo valor, y un único `print()` con bucle cuando hay varios.

## 1. Importar NumPy

Se importa con el alias `np`, que es la convención estándar.

In [1]:
import numpy as np

np.__version__

'2.5.3'

## 2. Crear un array con los números del 1 al 10

`np.arange(inicio, fin)` genera los valores desde `inicio` hasta `fin - 1`: el
límite superior es **excluyente**, por eso se escribe `11` para llegar al 10.

In [2]:
numeros = np.arange(1, 11)

numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 3. Valor máximo y mínimo

Las funciones `np.max()` / `np.min()` y los métodos equivalentes
`numeros.max()` / `numeros.min()` hacen exactamente lo mismo.

In [3]:
extremos = {
    "Valor máximo": numeros.max(),
    "Valor mínimo": numeros.min(),
}

for etiqueta, valor in extremos.items():
    print(f"{etiqueta}: {valor}")

Valor máximo: 10
Valor mínimo: 1


## 4 y 5. Array de 5 ceros y array de 5 unos

`np.zeros()` y `np.ones()` crean arrays del tamaño indicado rellenos con ese
valor. Por defecto son de tipo `float64`, por eso se muestran como `0.` y `1.`
en lugar de `0` y `1`.

In [4]:
ceros = np.zeros(5)
unos = np.ones(5)

arrays = {
    "Array de 5 ceros": ceros,
    "Array de 5 unos": unos,
    "Tipo de dato": ceros.dtype,
}

for etiqueta, valor in arrays.items():
    print(f"{etiqueta}: {valor}")

Array de 5 ceros: [0. 0. 0. 0. 0.]
Array de 5 unos: [1. 1. 1. 1. 1.]
Tipo de dato: float64


## 6 y 7. Crear la matriz y mostrarla

`np.array()` construye un array a partir de listas anidadas: cada lista interna
es una fila.

In [5]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

matrix

array([[1, 2, 3],
       [4, 5, 6]])

## 8. Dimensiones de la matriz con `.shape`

`.shape` devuelve una tupla `(filas, columnas)`: en este caso 2 filas y 3
columnas.

In [6]:
matrix.shape

(2, 3)

---

# Ejercicios adicionales

Los requisitos del enunciado terminan en el punto anterior. Lo que sigue es
práctica complementaria del grupo sobre atributos de arrays, indexación y
operaciones estadísticas.

## Atributos de un array

Todo array expone atributos que describen su estructura, sin necesidad de
recorrerlo:

| Atributo | Qué indica |
| --- | --- |
| `.shape` | forma: filas y columnas |
| `.ndim` | número de dimensiones (1 = vector, 2 = matriz) |
| `.size` | cantidad total de elementos |
| `.dtype` | tipo de dato de los elementos |

In [7]:
datos = np.array([10, 20, 30, 40, 50])

atributos = {
    "Array": datos,
    "Forma": datos.shape,
    "Dimensiones": datos.ndim,
    "N° elementos": datos.size,
    "Tipo de dato": datos.dtype,
}

for etiqueta, valor in atributos.items():
    print(f"{etiqueta}: {valor}")

Array: [10 20 30 40 50]
Forma: (5,)
Dimensiones: 1
N° elementos: 5
Tipo de dato: int64


## Los mismos atributos en una matriz de 3x3

Nótese que ahora `.ndim` es 2 y `.size` es 9, es decir, filas por columnas.

In [8]:
matriz = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

matriz

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
atributos = {
    "Forma": matriz.shape,
    "Dimensiones": matriz.ndim,
    "N° elementos": matriz.size,
}

for etiqueta, valor in atributos.items():
    print(f"{etiqueta}: {valor}")

Forma: (3, 3)
Dimensiones: 2
N° elementos: 9


## Indexación de filas y columnas

En una matriz se indica `[fila, columna]`. Los dos puntos `:` significan
"todos", por lo que `matriz[0, :]` es la primera fila completa y `matriz[:, 1]`
es la segunda columna completa.

In [10]:
seleccion = {
    "Elemento en fila 1, columna 1": matriz[1, 1],
    "Primera fila": matriz[0, :],
    "Segunda columna": matriz[:, 1],
}

for etiqueta, valor in seleccion.items():
    print(f"{etiqueta}: {valor}")

Elemento en fila 1, columna 1: 50
Primera fila: [10 20 30]
Segunda columna: [20 50 80]


## Operaciones estadísticas

Estas funciones recorren toda la matriz y devuelven un solo valor. No hace
falta ningún bucle: NumPy opera sobre el array completo.

In [11]:
estadisticas = {
    "Suma total": matriz.sum(),
    "Promedio": matriz.mean(),
    "Valor máximo": matriz.max(),
    "Valor mínimo": matriz.min(),
}

for etiqueta, valor in estadisticas.items():
    print(f"{etiqueta}: {valor}")

Suma total: 450
Promedio: 50.0
Valor máximo: 90
Valor mínimo: 10


## Promedios por eje

El parámetro `axis` define la dirección del cálculo:

- `axis=0` recorre **las filas** hacia abajo, así que devuelve un promedio
  **por columna**.
- `axis=1` recorre **las columnas** hacia el costado, así que devuelve un
  promedio **por fila**.

In [12]:
promedios = {
    "Promedio por columna (axis=0)": matriz.mean(axis=0),
    "Promedio por fila    (axis=1)": matriz.mean(axis=1),
}

for etiqueta, valor in promedios.items():
    print(f"{etiqueta}: {valor}")

Promedio por columna (axis=0): [40. 50. 60.]
Promedio por fila    (axis=1): [20. 50. 80.]


## Conclusión

NumPy permite aplicar operaciones sobre todos los elementos de un array a la
vez, sin escribir bucles. Los atributos `.shape`, `.ndim`, `.size` y `.dtype`
describen la estructura del array, mientras que funciones como `sum()`,
`mean()`, `max()` y `min()` resumen su contenido. El parámetro `axis` permite
además calcular esos resúmenes por fila o por columna.