# NumPy – Diplomado en Ciencia de Datos

**Estudiante:** Roddy Huarhua Rojas  
**Curso:** Ciencia de Datos  
**Tema:** Introducción y uso de NumPy

In [1]:
import numpy as np

print("NumPy funciona correctamente")
print("Versión:", np.__version__)

NumPy funciona correctamente
Versión: 2.5.3


In [10]:
numeros = np.arange(1, 11)

print("Array del 1 al 10:", numeros)

Array del 1 al 10: [ 1  2  3  4  5  6  7  8  9 10]


In [11]:
print("Valor máximo:", np.max(numeros))
print("Valor mínimo:", np.min(numeros))

Valor máximo: 10
Valor mínimo: 1


In [12]:
ceros = np.zeros(5)
unos = np.ones(5)

print("Array de 5 ceros:", ceros)
print("Array de 5 unos:", unos)

Array de 5 ceros: [0. 0. 0. 0. 0.]
Array de 5 unos: [1. 1. 1. 1. 1.]


In [13]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matriz:")
print(matrix)

print("Dimensiones de la matriz:", matrix.shape)

Matriz:
[[1 2 3]
 [4 5 6]]
Dimensiones de la matriz: (2, 3)


In [3]:
datos = np.array([10, 20, 30, 40, 50])

print(datos)

[10 20 30 40 50]


In [4]:
print("Cantidad de elementos:", datos.size)
print("Dimensiones:", datos.ndim)
print("Tipo de dato:", datos.dtype)

Cantidad de elementos: 5
Dimensiones: 1
Tipo de dato: int64


In [5]:
matriz = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(matriz)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [6]:
print("Forma de la matriz:", matriz.shape)
print("Dimensiones:", matriz.ndim)
print("Cantidad de elementos:", matriz.size)

Forma de la matriz: (3, 3)
Dimensiones: 2
Cantidad de elementos: 9


In [7]:
print("Elemento fila 1, columna 1:", matriz[1, 1])
print("Primera fila:", matriz[0, :])
print("Segunda columna:", matriz[:, 1])

Elemento fila 1, columna 1: 50
Primera fila: [10 20 30]
Segunda columna: [20 50 80]


In [8]:
print("Suma total:", np.sum(matriz))
print("Promedio:", np.mean(matriz))
print("Valor máximo:", np.max(matriz))
print("Valor mínimo:", np.min(matriz))

Suma total: 450
Promedio: 50.0
Valor máximo: 90
Valor mínimo: 10


In [9]:
print("Promedio por columna:", np.mean(matriz, axis=0))
print("Promedio por fila:", np.mean(matriz, axis=1))

Promedio por columna: [40. 50. 60.]
Promedio por fila: [20. 50. 80.]
